### ISSUE TITLE
IsDocumentReady set to false when secondary frames are being edited/unloaded

### ISSUE THREAD

**Issue by Perikles** [awesomium/awesomium-pub#75]
- http://answers.awesomium.com/questions/6010/
- http://answers.awesomium.com/questions/5965/
- http://answers.awesomium.com/questions/6041/

**Comment by sightlysam** [comment]
Is there a workaround or ETA on the fix for this issue?

**Comment by nhopp** [comment]
What is the ETA for this fix? We are seeing this happen frequently and is a serious regression.

**Comment by raslam** [comment]
Hi @Perikles 

when it ll be fixed?

This is the main hurdle in our project.

**Comment by Perikles** [comment]
The fix for this issue is included with the stable release of **v1.7.5** expected within the week.

**Comment by DoogShnooglis** [comment]
So what's the status of this issue? Still says open, and I can't find 1.7.5.1 anywhere. Expected within the week seven weeks ago. Is this still coming out?

**Comment by febret** [comment]
Good luck getting help. This project looks pretty much dead. It's a shame, it was really useful while it worked. :disappointed:

**Comment by GillesFr** [comment]
The bug is fixed !!! Version 1.7.5.1 is available (use the updater.exe located in "C:\Program Files (x86)\Awesomium Technologies LLC\Awesomium SDK" to update).
It works perfectly :-)
Many thanks to you Perikles ... great job !

**Comment by logikonline** [comment]
This still an error in the WinForm version
